### ISSUE TITLE
APIError: Invalid request made, key returns as undefined

### ISSUE THREAD

**Issue by HamburburDev** [TheDrone7/disco-oauth#29]
The full error is:
`APIError: Invalid request made
    at C:\Users\kubak\Desktop\breadbot\node_modules\disco-oauth\lib\client.js:106:23
    at processTicksAndRejections (node:internal/process/task_queues:93:5) {
  statusCode: 400
}`

My code:

`router.get('/auth',` async (req, res) => {
    try {
      const code = req.query.code;
      const key = await authClient.getAccess(code).catch(console.error);
      res.cookies.set('key', key);
      console.log(key)

      res.send(key)
    } catch(e) {
      res.redirect('errors/400')
    `}`
});`
The key returns as undefined

**Comment by TheDrone7** [comment]
Could you share your full code? I suspect it might be due to improper setup since that request is for getting the access token and needs you to have set up your redirect URIs, scopes, client ID and client secret.

**Comment by HamburburDev** [comment]
Yeah, here its a pastebin link:

https://pastebin.com/xFj3sE08

**Comment by TheDrone7** [comment]
Ok yeah this is due to improper setup.

On line 7, you set the internal redirect URI to `${config.dashboard.url}/auth` which can not be the same as `http%3A%2F%2Flocalhost%3A3000%2Fauth` which does not contain the `/`.
Note that even though they are essentially the same, discord needs the two values to be exactly the same, if you set the redirect URI in your dashboard to contain the encoded URI components, make sure all links in the setup also use encoded URI components, any decoded ones will cause errors.
