### ISSUE TITLE
getUser Invalid Key

### ISSUE THREAD

**Issue by exewax** [TheDrone7/disco-oauth#43]
Hello, small issue on .getUser(key)

When you call the getUser function with an invalid key the function does'nt reject with a new error but return a typeError :

`TypeError: Cannot read property 'access_token' of undefined`

**Comment by TheDrone7** [comment]
Can you give an example of the key being passed? The key needs to be a jwt token signed using your client's secret, as long as it is that, it will go through and make the request even if the key has expired.

In case it is not a jwt token signed by your client's secret, I am going to need some sample for which it seems to be working for you. Because in that case, it jwt should be throwing an error.

**Comment by exewax** [comment]
I gave a bad key on purpose, to imitate a user who changes the key in his cookies, bad news even with a try catch the server stop and return a typeError

**Comment by Zerglrisk** [comment]
yeah i have that problem. i put in that code in my middleware.

	fetchUser: async (req, res, next) => {
	try{
		const userKey = res.cookies.get('key');
		if(userKey){
			res.locals.user = await oAuthclient.getUser(userKey);
		}
	} catch(error) {
		console.log(`middleware.updateUser Error : ${error.message}`);
	} finally {
		next();
		}
	}

it shows error from getting undefined access. and it not come into catch.
sometimes if dont have key but express throw [Object object] idk why, i have to find out
anyway, point is. if enter bad key, must got error and program stopping.

so i just fix the code that here

	.......
	if(!access){
		reject(new Error('Invalid key provided.'));
		return;
	}
	const token = access['access_token'],
	.......

**Comment by TheDrone7** [comment]
Thanks for bringing this forward. I apologize for the delay but it has been fixed, just published a new version `5.1.1` of the library with the fix.
