### ISSUE TITLE
Error: Invalid request made

### ISSUE THREAD

**Issue by TheGoldenCactus11** [TheDrone7/disco-oauth#8]
**To Reproduce**
myClient.getAccess(req.query.code)

**Expected behavior**
Return Access Key

**Actual behavior**
Error: Invalid request made

**Screenshots**

**Specifications**
node.js: v10.16.0
disco-oauth: `4.2.1`

**Suggestions**
Bad code

**Additional context**
(node:735) UnhandledPromiseRejectionWarning: Error: Invalid request made
    at Promise (/home/runner/node_modules/disco-oauth/lib/client.js:106:23)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:735) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 5)

**Comment by asadhum2005** [comment]
I am having the same issue, please make sure that it works!

**Comment by TheDrone7** [comment]
Here's a live example for the library - https://express-ejs.thedrone7.repl.co/

Source code at https://express-ejs.thedrone7.repl.co/__repl

And also available in the examples branch. The issue you have is due to some sort of improper implementation of your server. This is not an issue with the library.
